export const CONTRACT_STATUS = [
    "NEW",
    "PRE_EXPIRY",
    "EXPIRED",
    "POST_EXPIRY",
    "INACTIVE",
    "TERMINATED",
] as const;// Add local constant for roles
export const USER_ROLES = [
  "CONTRACT_MANAGER",
  "CONTRACT_OWNER",
  "CATEGORY_SOURCING_MANAGER",
  "LEGAL_TEAM",

] as const;

export enum CONTRACT_TYPE {
  ADDENDUM = "Addendum",
  ATTACHMENT = "Attachment",
  AMENDMENT = "Amendment",
  CHANGE_REQUEST = "Change Request",
  EXTENSION_RENEWAL = "Extension/Renewal",
  LOCAL_AGREEMENT = "Local Agreement",
  MASTER_AGREEMENT = "Master Agreement",
  SALES_ORDER = "Sales Order",
  SERVICE_AGREEMENT = "Service Agreement",
  STATEMENT_OF_WORK = "Statement of Work"
}

export enum TERM_TYPE {
  AUTO_RENEWAL = "Auto-Renewal",
  FIXED = "Fixed",
  PERPETUAL = "Perpetual"
}

export enum SUPPLIER_SERVICE {
  ADVERTISING_SERVICES = "ADVERTISING SERVICES",
  ARTS_CULTURE = "ARTS & CULTURE",
  ASSET_TRACKING_SERVICES = "ASSET TRACKING SERVICES",
  AUDIO_VISUAL_SERVICES = "AUDIO VISUAL SERVICES",
  AUDIT_SERVICES = "AUDIT SERVICES",
  BROADBAND_FIBER_WIMAX = "BROADBAND FIBER WIMAX INSTALTN",
  BTS_CONSTRUCTION = "BTS CONTSTRUCTION/CIVIL WORKS",
  BTS_LANDLORDS = "BTS LANDLORDS",
  BUILDING_CONSTRUCTION = "BUILDING CONSTRUCTION SERVICES",
  BUSINESS_CONSULTANCY = "BUSINESS CONSULTANCY SERVICES",
  CATERING_HOSPITALITY = "CATERING & HOSPITALITY",
  CLEANING_LANDSCAPING = "CLEANING AND LANDSCAPING",
  CLEANING_SERVICES = "CLEANING SERVICES",
  COMPANY = "COMPANY",
  COMPUTER_CONSUMABLES = "COMPUTER CONSUMABLES",
  CONSTRUCTION_PERMIT = "CONSTRUCTION PERMIT WORKERS",
  CONTRACTORS = "CONTRACTORS",
  DEALER = "DEALER",
  DISBURSEMENTS = "DISBURSEMENTS -OTHERS",
  DISTRIBUTION = "DISTRBTN INBOUND & WAREHSNG",
  EDUCATION = "EDUCATION",
  ELECTRICAL_FITTINGS = "ELECTRICAL FITTINGS",
  EVENT_MANAGEMENT = "EVENT MANAGEMENT SERVICES",
  FACILITIES_MAINTENANCE = "FACILITIES MAINTENANCE & REPAI",
  FLEET_MAINTENANCE = "FLEET MAINTENANCE & REPAIRS",
  FLEET_MANAGEMENT = "FLEET MANAGEMENT SERVICES",
  FLEET_FUEL = "FLEET MANAGEMENT-FUEL",
  FOREIGN_SERVICES = "FOREIGN SERVICES",
  FURNITURE_FITTINGS = "FURNITURE AND FITTINGS",
  GENERAL_CONSULTANCY = "GENERAL CONSULTANCY SERVICES",
  GENERAL_SUPPLIERS = "GENERAL SUPPLIERS",
  GOVERNMENT = "GOVERNMENT",
  HEALTH = "HEALTH",
  HOSPITALITY = "HOSPITALITY SERVICES",
  HR_SERVICES = "HR SERVICES-STAFF WELFARE",
  INSURANCE = "INSURANCE SERVICES",
  INTERCONNECT = "INTERCONNECT & ROAMING",
  IT_APPLICATIONS = "IT APPLICATIONS SOFTWARE",
  IT_CLOUD = "IT CLOUD SERVICES",
  IT_LICENSES = "IT ENTERPRISE LICENSES",
  IT_INFRASTRUCTURE = "IT INFRASTRUCTURE SERVICES",
  IT_MAINTENANCE = "IT MAINTENANCE & SUPPORT",
  IT_SECURITY = "IT SECURITY SERVICES",
  IT_IMPLEMENTATION = "IT SOFTWARE IMPLEMENTATION",
  IT_VAS_DEV = "IT/VAS DEV PROF SERVICES",
  IT_VAS_HARDWARE = "IT/VAS HARDWARE SUPPLY",
  IT_VAS_PLATFORMS = "IT/VAS PLATFORMS",
  IT_VAS_SECURITY = "IT/VAS SECURITY",
  IT_VAS_SUPPORT = "IT/VAS SUPPORT SERVICES",
  KNOW_AND_GROW = "KNOW AND GROW",
  LEGAL_SERVICES = "LEGAL SERVICES",
  LINK_RENTAL = "LINK RENTAL",
  LOGISTICS = "LOGISTICS SERVICES",
  MARKETING_ADVERT = "MARKETING & ADVERT SERVICES",
  MARKETING_ACTIVATIONS = "MARKETING ACTIVATIONS",
  MARKETING_SERVICES = "MARKETING SERVICES",
  MOTOR_LEASING = "MOTOR VEHICLE LEASING",
  MOTOR_PURCHASE = "MOTOR VEHICLE PURCHASE",
  MOTOR_VEHICLES = "MOTOR VEHICLES",
  MUNICIPALITY = "MUNICIPALITY",
  NETWORK_EQUIPMENT = "NETWORK EQUIPMENT",
  NETWORK_INFRA_ACC = "NETWORK INFRASTRUCTURE ACC.",
  NETWORK_INFRA_SERV = "NETWORK INFRASTRUCTURE SERV.",
  NETWORK_OPTIMIZATION = "NETWORK OPTIMISATION SERVICES",
  NETWORK_POWER = "NETWORK POWER INFRASTRUCTURE",
  OFFICE_CONSUMABLES = "OFFICE CONSUMABLES",
  OFFICE_FURNITURE = "OFFICE FURNITURE",
  OTHERS = "OTHERS",
  PARTNERSHIP = "PARTNERSHIP",
  PAYMENT_SERVICES = "PAYMENT SERVICES",
  PN_VENDOR = "PN_VENDOR",
  POSTPAID = "POSTPAID",
  PRINTING = "PRINTING SERVICES",
  PROFESSIONAL_TECHNICAL = "PROFESSIONAL & TECHNICAL",
  PROFESSIONAL_MEMBERSHIP = "PROFESSIONAL MEMBERSHIP",
  PROFESSIONAL_SUBSCRIPTIONS = "PROFESSIONAL SUBSCRIPTIONS",
  PROPERTY_LEASING = "PROPERTY LEASING",
  PROPERTY_SERVICES = "PROPERTY PROFESSIONAL SERVICES",
  PRS_PROVIDERS = "PRS PROVIDERS",
  RECRUITMENT = "RECRUITMENT SERVICES",
  RELATED_PARTY = "RELATED PARTY",
  RESEARCH = "RESEARCH SERVICES",
  RESIDENTIAL_LANDLORDS = "RESIDENTIAL LANDLORDS",
  ROAMING = "ROAMING",
  SAFARICOM_INTERNAL = "SAFARICOM INTERNAL SUPPLIER",
  SECURITY_SERVICES = "SECURITY SERVICES",
  SECURITY_SYSTEMS = "SECURITY SYSTEMS & SUPPORT",
  SECURITY_GUARDING = "SECURITY/GUARDING SERVICES",
  SITE_ACQUISITIONS = "SITE ACQUISITIONS SEVICES",
  SPONSORSHIPS = "SPONSORSHIPS",
  STAFF_HIRING = "STAFF HIRING SERVICES",
  STAFF_TRANSPORT = "STAFF TRANSPORT",
  STATIONERY = "STATIONERY AND CONSUMABLES",
  STATUTORY = "STATUTORY INSTITUTIONS",
  STRATEGIC_CONSULTANCY = "STRATEGIC CONSULTANCY",
  SUPPLY_TERMINALS = "SUPPLYTERMINALS DEVICES",
  T_SUPPLY = "T SUPPLY",
  TAX_AUTHORITY = "TAX AUTHORITY",
  TAXI_SUPPLIER = "TAXI SUPPLIER",
  TERMINAL_DEVICES = "TERMINAL DEVICES",
  TERMINALS = "TERMINALS",
  TRAINING = "TRAINING SERVICES",
  TRAVEL_ACCOMMODATION = "TRAVEL & ACCOMODATION",
  TRAVEL_MANAGEMENT = "TRAVEL MANAGEMENT SERVICES",
  UTILITIES = "UTILITIES",
  VAS_PLATFORMS = "VAS PLATFORMS AND SOLUTIONS",
  VENDOR = "VENDOR",
  WASTE_MANAGEMENT = "WASTE MANAGEMENT SERVICES"
}

export enum CURRENCY {
  ETB = "ETB",
  EUR = "EUR",
  KES = "KES",
  ZAR = "ZAR",
  GBP = "GBP",
  USD = "USD"
}

export enum COUNTRY {
  AFGHANISTAN = "Afghanistan",
  ALBANIA = "Albania",
  ALGERIA = "Algeria",
  ANDORRA = "Andorra",
  ANGOLA = "Angola",
  ANTIGUA_BARBUDA = "Antigua and Barbuda",
  ARGENTINA = "Argentina",
  ARMENIA = "Armenia",
  AUSTRALIA = "Australia",
  AUSTRIA = "Austria",
  AZERBAIJAN = "Azerbaijan",
  BAHAMAS = "Bahamas",
  BAHRAIN = "Bahrain",
  BANGLADESH = "Bangladesh",
  BARBADOS = "Barbados",
  BELARUS = "Belarus",
  BELGIUM = "Belgium",
  BELIZE = "Belize",
  BENIN = "Benin",
  BHUTAN = "Bhutan",
  BOLIVIA = "Bolivia",
  BOSNIA_HERZEGOVINA = "Bosnia and Herzegovina",
  BOTSWANA = "Botswana",
  BRAZIL = "Brazil",
  BRUNEI = "Brunei",
  BULGARIA = "Bulgaria",
  BURKINA_FASO = "Burkina Faso",
  BURUNDI = "Burundi",
  CAMBODIA = "Cambodia",
  CAMEROON = "Cameroon",
  CANADA = "Canada",
  CAPE_VERDE = "Cape Verde",
  CENTRAL_AFRICAN_REPUBLIC = "Central African Republic",
  CHAD = "Chad",
  CHILE = "Chile",
  CHINA = "China",
  COLOMBIA = "Colombia",
  COMOROS = "Comoros",
  CONGO = "Congo",
  DEMOCRATIC_REPUBLIC_CONGO = "Democratic Republic of the Congo",
  COSTA_RICA = "Costa Rica",
  IVORY_COAST = "Ivory Coast",
  CROATIA = "Croatia",
  CUBA = "Cuba",
  CYPRUS = "Cyprus",
  CZECH_REPUBLIC = "Czech Republic",
  DENMARK = "Denmark",
  DJIBOUTI = "Djibouti",
  DOMINICA = "Dominica",
  DOMINICAN_REPUBLIC = "Dominican Republic",
  ECUADOR = "Ecuador",
  EGYPT = "Egypt",
  EL_SALVADOR = "El Salvador",
  EQUATORIAL_GUINEA = "Equatorial Guinea",
  ERITREA = "Eritrea",
  ESTONIA = "Estonia",
  ETHIOPIA = "Ethiopia",
  FIJI = "Fiji",
  FINLAND = "Finland",
  FRANCE = "France",
  GABON = "Gabon",
  GAMBIA = "Gambia",
  GEORGIA = "Georgia",
  GERMANY = "Germany",
  GHANA = "Ghana",
  GREECE = "Greece",
  GRENADA = "Grenada",
  GUATEMALA = "Guatemala",
  GUINEA = "Guinea",
  GUINEA_BISSAU = "Guinea-Bissau",
  GUYANA = "Guyana",
  HAITI = "Haiti",
  HONDURAS = "Honduras",
  HONG_KONG = "Hong Kong",
  HUNGARY = "Hungary",
  ICELAND = "Iceland",
  INDIA = "India",
  INDONESIA = "Indonesia",
  IRAN = "Iran",
  IRAQ = "Iraq",
  IRELAND = "Ireland",
  ISRAEL = "Israel",
  ITALY = "Italy",
  JAMAICA = "Jamaica",
  JAPAN = "Japan",
  JORDAN = "Jordan",
  KAZAKHSTAN = "Kazakhstan",
  KENYA = "Kenya",
  KIRIBATI = "Kiribati",
  NORTH_KOREA = "North Korea",
  SOUTH_KOREA = "South Korea",
  KUWAIT = "Kuwait",
  KYRGYZSTAN = "Kyrgyzstan",
  LAOS = "Laos",
  LATVIA = "Latvia",
  LEBANON = "Lebanon",
  LESOTHO = "Lesotho",
  LIBERIA = "Liberia",
  LIBYA = "Libya",
  LIECHTENSTEIN = "Liechtenstein",
  LITHUANIA = "Lithuania",
  LUXEMBOURG = "Luxembourg",
  MACAU = "Macau",
  NORTH_MACEDONIA = "North Macedonia",
  MADAGASCAR = "Madagascar",
  MALAWI = "Malawi",
  MALAYSIA = "Malaysia",
  MALDIVES = "Maldives",
  MALI = "Mali",
  MALTA = "Malta",
  MARSHALL_ISLANDS = "Marshall Islands",
  MAURITANIA = "Mauritania",
  MAURITIUS = "Mauritius",
  MEXICO = "Mexico",
  MICRONESIA = "Micronesia",
  MOLDOVA = "Moldova",
  MONACO = "Monaco",
  MONGOLIA = "Mongolia",
  MONTENEGRO = "Montenegro",
  MOROCCO = "Morocco",
  MOZAMBIQUE = "Mozambique",
  MYANMAR = "Myanmar",
  NAMIBIA = "Namibia",
  NAURU = "Nauru",
  NEPAL = "Nepal",
  NETHERLANDS = "Netherlands",
  NEW_ZEALAND = "New Zealand",
  NICARAGUA = "Nicaragua",
  NIGER = "Niger",
  NIGERIA = "Nigeria",
  NORWAY = "Norway",
  OMAN = "Oman",
  PAKISTAN = "Pakistan",
  PALAU = "Palau",
  PALESTINE = "Palestine",
  PANAMA = "Panama",
  PAPUA_NEW_GUINEA = "Papua New Guinea",
  PARAGUAY = "Paraguay",
  PERU = "Peru",
  PHILIPPINES = "Philippines",
  POLAND = "Poland",
  PORTUGAL = "Portugal",
  QATAR = "Qatar",
  ROMANIA = "Romania",
  RUSSIA = "Russia",
  RWANDA = "Rwanda",
  SAINT_KITTS_NEVIS = "Saint Kitts and Nevis",
  SAINT_LUCIA = "Saint Lucia",
  SAINT_VINCENT_GRENADINES = "Saint Vincent and the Grenadines",
  SAMOA = "Samoa",
  SAN_MARINO = "San Marino",
  SAO_TOME_PRINCIPE = "Sao Tome and Principe",
  SAUDI_ARABIA = "Saudi Arabia",
  SENEGAL = "Senegal",
  SERBIA = "Serbia",
  SEYCHELLES = "Seychelles",
  SIERRA_LEONE = "Sierra Leone",
  SINGAPORE = "Singapore",
  SLOVAKIA = "Slovakia",
  SLOVENIA = "Slovenia",
  SOLOMON_ISLANDS = "Solomon Islands",
  SOMALIA = "Somalia",
  SOUTH_AFRICA = "South Africa",
  SOUTH_SUDAN = "South Sudan",
  SPAIN = "Spain",
  SRI_LANKA = "Sri Lanka",
  SUDAN = "Sudan",
  SURINAME = "Suriname",
  SWEDEN = "Sweden",
  SWITZERLAND = "Switzerland",
  SYRIA = "Syria",
  TAIWAN = "Taiwan",
  TAJIKISTAN = "Tajikistan",
  TANZANIA = "Tanzania",
  THAILAND = "Thailand",
  EAST_TIMOR = "East Timor",
  TOGO = "Togo",
  TONGA = "Tonga",
  TRINIDAD_TOBAGO = "Trinidad and Tobago",
  TUNISIA = "Tunisia",
  TURKEY = "Turkey",
  TURKMENISTAN = "Turkmenistan",
  TUVALU = "Tuvalu",
  UGANDA = "Uganda",
  UKRAINE = "Ukraine",
  UNITED_ARAB_EMIRATES = "United Arab Emirates",
  UNITED_KINGDOM = "United Kingdom",
  UNITED_STATES = "United States",
  URUGUAY = "Uruguay",
  UZBEKISTAN = "Uzbekistan",
  VANUATU = "Vanuatu",
  VATICAN_CITY = "Vatican City",
  VENEZUELA = "Venezuela",
  VIETNAM = "Vietnam",
  YEMEN = "Yemen",
  ZAMBIA = "Zambia",
  ZIMBABWE = "Zimbabwe"
}

export const CONTRACT_TYPE_OPTIONS = Object.entries(CONTRACT_TYPE).map(([key, value]) => ({
  label: value,
  value: value,
  description: getContractTypeDescription(value),
}));

export const TERM_TYPE_OPTIONS = Object.entries(TERM_TYPE).map(([key, value]) => ({
  label: value,
  value: value,
  description: getTermTypeDescription(value),
}));

export const SUPPLIER_SERVICE_OPTIONS = Object.entries(SUPPLIER_SERVICE).map(([key, value]) => ({
  label: value,
  value: value,
  description: getSupplierServiceDescription(value),
}));

export const CURRENCY_OPTIONS = Object.entries(CURRENCY).map(([key, value]) => ({
  label: value,
  value: value,
  description: getCurrencyDescription(value)
}));

export const COUNTRY_OPTIONS = [
  { value: "AF", label: "Afghanistan", description: "Islamic Republic of Afghanistan" },
  { value: "AL", label: "Albania", description: "Republic of Albania" },
  { value: "DZ", label: "Algeria", description: "People's Democratic Republic of Algeria" },
  { value: "AD", label: "Andorra", description: "Principality of Andorra" },
  { value: "AO", label: "Angola", description: "Republic of Angola" },
  { value: "AG", label: "Antigua and Barbuda", description: "Antigua and Barbuda" },
  { value: "AR", label: "Argentina", description: "Argentine Republic" },
  { value: "AM", label: "Armenia", description: "Republic of Armenia" },
  { value: "AU", label: "Australia", description: "Commonwealth of Australia" },
  { value: "AT", label: "Austria", description: "Republic of Austria" },
  { value: "AZ", label: "Azerbaijan", description: "Republic of Azerbaijan" },
  { value: "BS", label: "Bahamas", description: "Commonwealth of The Bahamas" },
  { value: "BH", label: "Bahrain", description: "Kingdom of Bahrain" },
  { value: "BD", label: "Bangladesh", description: "People's Republic of Bangladesh" },
  { value: "BB", label: "Barbados", description: "Barbados" },
  { value: "BY", label: "Belarus", description: "Republic of Belarus" },
  { value: "BE", label: "Belgium", description: "Kingdom of Belgium" },
  { value: "BZ", label: "Belize", description: "Belize" },
  { value: "BJ", label: "Benin", description: "Republic of Benin" },
  { value: "BT", label: "Bhutan", description: "Kingdom of Bhutan" },
  { value: "BO", label: "Bolivia", description: "Plurinational State of Bolivia" },
  { value: "BA", label: "Bosnia and Herzegovina", description: "Bosnia and Herzegovina" },
  { value: "BW", label: "Botswana", description: "Republic of Botswana" },
  { value: "BR", label: "Brazil", description: "Federative Republic of Brazil" },
  { value: "BN", label: "Brunei", description: "Brunei Darussalam" },
  { value: "BG", label: "Bulgaria", description: "Republic of Bulgaria" },
  { value: "BF", label: "Burkina Faso", description: "Burkina Faso" },
  { value: "BI", label: "Burundi", description: "Republic of Burundi" },
  { value: "KH", label: "Cambodia", description: "Kingdom of Cambodia" },
  { value: "CM", label: "Cameroon", description: "Republic of Cameroon" },
  { value: "CA", label: "Canada", description: "Canada" },
  { value: "CV", label: "Cape Verde", description: "Republic of Cabo Verde" },
  { value: "CF", label: "Central African Republic", description: "Central African Republic" },
  { value: "TD", label: "Chad", description: "Republic of Chad" },
  { value: "CL", label: "Chile", description: "Republic of Chile" },
  { value: "CN", label: "China", description: "People's Republic of China" },
  { value: "CO", label: "Colombia", description: "Republic of Colombia" },
  { value: "KM", label: "Comoros", description: "Union of the Comoros" },
  { value: "CG", label: "Congo", description: "Republic of the Congo" },
  { value: "CD", label: "Democratic Republic of the Congo", description: "Democratic Republic of the Congo" },
  { value: "CR", label: "Costa Rica", description: "Republic of Costa Rica" },
  { value: "CI", label: "Ivory Coast", description: "Republic of Côte d'Ivoire" },
  { value: "HR", label: "Croatia", description: "Republic of Croatia" },
  { value: "CU", label: "Cuba", description: "Republic of Cuba" },
  { value: "CY", label: "Cyprus", description: "Republic of Cyprus" },
  { value: "CZ", label: "Czech Republic", description: "Czech Republic" },
  { value: "DK", label: "Denmark", description: "Kingdom of Denmark" },
  { value: "DJ", label: "Djibouti", description: "Republic of Djibouti" },
  { value: "DM", label: "Dominica", description: "Commonwealth of Dominica" },
  { value: "DO", label: "Dominican Republic", description: "Dominican Republic" },
  { value: "EC", label: "Ecuador", description: "Republic of Ecuador" },
  { value: "EG", label: "Egypt", description: "Arab Republic of Egypt" },
  { value: "SV", label: "El Salvador", description: "Republic of El Salvador" },
  { value: "GQ", label: "Equatorial Guinea", description: "Republic of Equatorial Guinea" },
  { value: "ER", label: "Eritrea", description: "State of Eritrea" },
  { value: "EE", label: "Estonia", description: "Republic of Estonia" },
  { value: "ET", label: "Ethiopia", description: "Federal Democratic Republic of Ethiopia" },
  { value: "FJ", label: "Fiji", description: "Republic of Fiji" },
  { value: "FI", label: "Finland", description: "Republic of Finland" },
  { value: "FR", label: "France", description: "French Republic" },
  { value: "GA", label: "Gabon", description: "Gabonese Republic" },
  { value: "GM", label: "Gambia", description: "Republic of The Gambia" },
  { value: "GE", label: "Georgia", description: "Georgia" },
  { value: "DE", label: "Germany", description: "Federal Republic of Germany" },
  { value: "GH", label: "Ghana", description: "Republic of Ghana" },
  { value: "GR", label: "Greece", description: "Hellenic Republic" },
  { value: "GD", label: "Grenada", description: "Grenada" },
  { value: "GT", label: "Guatemala", description: "Republic of Guatemala" },
  { value: "GN", label: "Guinea", description: "Republic of Guinea" },
  { value: "GW", label: "Guinea-Bissau", description: "Republic of Guinea-Bissau" },
  { value: "GY", label: "Guyana", description: "Co-operative Republic of Guyana" },
  { value: "HT", label: "Haiti", description: "Republic of Haiti" },
  { value: "HN", label: "Honduras", description: "Republic of Honduras" },
  { value: "HK", label: "Hong Kong", description: "Hong Kong Special Administrative Region of China" },
  { value: "HU", label: "Hungary", description: "Hungary" },
  { value: "IS", label: "Iceland", description: "Iceland" },
  { value: "IN", label: "India", description: "Republic of India" },
  { value: "ID", label: "Indonesia", description: "Republic of Indonesia" },
  { value: "IR", label: "Iran", description: "Islamic Republic of Iran" },
  { value: "IQ", label: "Iraq", description: "Republic of Iraq" },
  { value: "IE", label: "Ireland", description: "Ireland" },
  { value: "IL", label: "Israel", description: "State of Israel" },
  { value: "IT", label: "Italy", description: "Italian Republic" },
  { value: "JM", label: "Jamaica", description: "Jamaica" },
  { value: "JP", label: "Japan", description: "Japan" },
  { value: "JO", label: "Jordan", description: "Hashemite Kingdom of Jordan" },
  { value: "KZ", label: "Kazakhstan", description: "Republic of Kazakhstan" },
  { value: "KE", label: "Kenya", description: "Republic of Kenya" },
  { value: "KI", label: "Kiribati", description: "Republic of Kiribati" },
  { value: "KP", label: "North Korea", description: "Democratic People's Republic of Korea" },
  { value: "KR", label: "South Korea", description: "Republic of Korea" },
  { value: "KW", label: "Kuwait", description: "State of Kuwait" },
  { value: "KG", label: "Kyrgyzstan", description: "Kyrgyz Republic" },
  { value: "LA", label: "Laos", description: "Lao People's Democratic Republic" },
  { value: "LV", label: "Latvia", description: "Republic of Latvia" },
  { value: "LB", label: "Lebanon", description: "Lebanese Republic" },
  { value: "LS", label: "Lesotho", description: "Kingdom of Lesotho" },
  { value: "LR", label: "Liberia", description: "Republic of Liberia" },
  { value: "LY", label: "Libya", description: "State of Libya" },
  { value: "LI", label: "Liechtenstein", description: "Principality of Liechtenstein" },
  { value: "LT", label: "Lithuania", description: "Republic of Lithuania" },
  { value: "LU", label: "Luxembourg", description: "Grand Duchy of Luxembourg" },
  { value: "MO", label: "Macau", description: "Macao Special Administrative Region of China" },
  { value: "MK", label: "North Macedonia", description: "Republic of North Macedonia" },
  { value: "MG", label: "Madagascar", description: "Republic of Madagascar" },
  { value: "MW", label: "Malawi", description: "Republic of Malawi" },
  { value: "MY", label: "Malaysia", description: "Malaysia" },
  { value: "MV", label: "Maldives", description: "Republic of Maldives" },
  { value: "ML", label: "Mali", description: "Republic of Mali" },
  { value: "MT", label: "Malta", description: "Republic of Malta" },
  { value: "MH", label: "Marshall Islands", description: "Republic of the Marshall Islands" },
  { value: "MR", label: "Mauritania", description: "Islamic Republic of Mauritania" },
  { value: "MU", label: "Mauritius", description: "Republic of Mauritius" },
  { value: "MX", label: "Mexico", description: "United Mexican States" },
  { value: "FM", label: "Micronesia", description: "Federated States of Micronesia" },
  { value: "MD", label: "Moldova", description: "Republic of Moldova" },
  { value: "MC", label: "Monaco", description: "Principality of Monaco" },
  { value: "MN", label: "Mongolia", description: "Mongolia" },
  { value: "ME", label: "Montenegro", description: "Montenegro" },
  { value: "MA", label: "Morocco", description: "Kingdom of Morocco" },
  { value: "MZ", label: "Mozambique", description: "Republic of Mozambique" },
  { value: "MM", label: "Myanmar", description: "Republic of the Union of Myanmar" },
  { value: "NA", label: "Namibia", description: "Republic of Namibia" },
  { value: "NR", label: "Nauru", description: "Republic of Nauru" },
  { value: "NP", label: "Nepal", description: "Federal Democratic Republic of Nepal" },
  { value: "NL", label: "Netherlands", description: "Kingdom of the Netherlands" },
  { value: "NZ", label: "New Zealand", description: "New Zealand" },
  { value: "NI", label: "Nicaragua", description: "Republic of Nicaragua" },
  { value: "NE", label: "Niger", description: "Republic of Niger" },
  { value: "NG", label: "Nigeria", description: "Federal Republic of Nigeria" },
  { value: "NO", label: "Norway", description: "Kingdom of Norway" },
  { value: "OM", label: "Oman", description: "Sultanate of Oman" },
  { value: "PK", label: "Pakistan", description: "Islamic Republic of Pakistan" },
  { value: "PW", label: "Palau", description: "Republic of Palau" },
  { value: "PS", label: "Palestine", description: "State of Palestine" },
  { value: "PA", label: "Panama", description: "Republic of Panama" },
  { value: "PG", label: "Papua New Guinea", description: "Independent State of Papua New Guinea" },
  { value: "PY", label: "Paraguay", description: "Republic of Paraguay" },
  { value: "PE", label: "Peru", description: "Republic of Peru" },
  { value: "PH", label: "Philippines", description: "Republic of the Philippines" },
  { value: "PL", label: "Poland", description: "Republic of Poland" },
  { value: "PT", label: "Portugal", description: "Portuguese Republic" },
  { value: "QA", label: "Qatar", description: "State of Qatar" },
  { value: "RO", label: "Romania", description: "Romania" },
  { value: "RU", label: "Russia", description: "Russian Federation" },
  { value: "RW", label: "Rwanda", description: "Republic of Rwanda" },
  { value: "KN", label: "Saint Kitts and Nevis", description: "Federation of Saint Christopher and Nevis" },
  { value: "LC", label: "Saint Lucia", description: "Saint Lucia" },
  { value: "VC", label: "Saint Vincent and the Grenadines", description: "Saint Vincent and the Grenadines" },
  { value: "WS", label: "Samoa", description: "Independent State of Samoa" },
  { value: "SM", label: "San Marino", description: "Republic of San Marino" },
  { value: "ST", label: "Sao Tome and Principe", description: "Democratic Republic of São Tomé and Príncipe" },
  { value: "SA", label: "Saudi Arabia", description: "Kingdom of Saudi Arabia" },
  { value: "SN", label: "Senegal", description: "Republic of Senegal" },
  { value: "RS", label: "Serbia", description: "Republic of Serbia" },
  { value: "SC", label: "Seychelles", description: "Republic of Seychelles" },
  { value: "SL", label: "Sierra Leone", description: "Republic of Sierra Leone" },
  { value: "SG", label: "Singapore", description: "Republic of Singapore" },
  { value: "SK", label: "Slovakia", description: "Slovak Republic" },
  { value: "SI", label: "Slovenia", description: "Republic of Slovenia" },
  { value: "SB", label: "Solomon Islands", description: "Solomon Islands" },
  { value: "SO", label: "Somalia", description: "Federal Republic of Somalia" },
  { value: "ZA", label: "South Africa", description: "Republic of South Africa" },
  { value: "SS", label: "South Sudan", description: "Republic of South Sudan" },
  { value: "ES", label: "Spain", description: "Kingdom of Spain" },
  { value: "LK", label: "Sri Lanka", description: "Democratic Socialist Republic of Sri Lanka" },
  { value: "SD", label: "Sudan", description: "Republic of the Sudan" },
  { value: "SR", label: "Suriname", description: "Republic of Suriname" },
  { value: "SE", label: "Sweden", description: "Kingdom of Sweden" },
  { value: "CH", label: "Switzerland", description: "Swiss Confederation" },
  { value: "SY", label: "Syria", description: "Syrian Arab Republic" },
  { value: "TW", label: "Taiwan", description: "Republic of China (Taiwan)" },
  { value: "TJ", label: "Tajikistan", description: "Republic of Tajikistan" },
  { value: "TZ", label: "Tanzania", description: "United Republic of Tanzania" },
  { value: "TH", label: "Thailand", description: "Kingdom of Thailand" },
  { value: "TL", label: "East Timor", description: "Democratic Republic of Timor-Leste" },
  { value: "TG", label: "Togo", description: "Togolese Republic" },
  { value: "TO", label: "Tonga", description: "Kingdom of Tonga" },
  { value: "TT", label: "Trinidad and Tobago", description: "Republic of Trinidad and Tobago" },
  { value: "TN", label: "Tunisia", description: "Republic of Tunisia" },
  { value: "TR", label: "Turkey", description: "Republic of Turkey" },
  { value: "TM", label: "Turkmenistan", description: "Turkmenistan" },
  { value: "TV", label: "Tuvalu", description: "Tuvalu" },
  { value: "UG", label: "Uganda", description: "Republic of Uganda" },
  { value: "UA", label: "Ukraine", description: "Ukraine" },
  { value: "AE", label: "United Arab Emirates", description: "United Arab Emirates" },
  { value: "GB", label: "United Kingdom", description: "United Kingdom of Great Britain and Northern Ireland" },
  { value: "US", label: "United States", description: "United States of America" },
  { value: "UY", label: "Uruguay", description: "Oriental Republic of Uruguay" },
  { value: "UZ", label: "Uzbekistan", description: "Republic of Uzbekistan" },
  { value: "VU", label: "Vanuatu", description: "Republic of Vanuatu" },
  { value: "VA", label: "Vatican City", description: "Vatican City State" },
  { value: "VE", label: "Venezuela", description: "Bolivarian Republic of Venezuela" },
  { value: "VN", label: "Vietnam", description: "Socialist Republic of Vietnam" },
  { value: "YE", label: "Yemen", description: "Republic of Yemen" },
  { value: "ZM", label: "Zambia", description: "Republic of Zambia" },
  { value: "ZW", label: "Zimbabwe", description: "Republic of Zimbabwe" }
];

function getContractTypeDescription(type: CONTRACT_TYPE): string {
  const descriptions: Record<CONTRACT_TYPE, string> = {
    [CONTRACT_TYPE.ADDENDUM]: "Document that adds or modifies terms of an existing contract",
    [CONTRACT_TYPE.ATTACHMENT]: "Supplementary document attached to the main contract",
    [CONTRACT_TYPE.AMENDMENT]: "Formal change to the terms of an existing contract",
    [CONTRACT_TYPE.CHANGE_REQUEST]: "Proposal to modify the scope or terms of a contract",
    [CONTRACT_TYPE.EXTENSION_RENEWAL]: "Extension of an existing contract's term",
    [CONTRACT_TYPE.LOCAL_AGREEMENT]: "Agreement specific to a particular location or jurisdiction",
    [CONTRACT_TYPE.MASTER_AGREEMENT]: "Framework agreement that sets terms for future transactions",
    [CONTRACT_TYPE.SALES_ORDER]: "Document confirming the sale of goods or services",
    [CONTRACT_TYPE.SERVICE_AGREEMENT]: "Agreement for the provision of services",
    [CONTRACT_TYPE.STATEMENT_OF_WORK]: "Detailed description of work to be performed"
  };
  return descriptions[type];
}

function getTermTypeDescription(type: TERM_TYPE): string {
  const descriptions: Record<TERM_TYPE, string> = {
    [TERM_TYPE.AUTO_RENEWAL]: "Contract automatically renews for a specified period unless notice is given",
    [TERM_TYPE.FIXED]: "Contract has a fixed start and end date",
    [TERM_TYPE.PERPETUAL]: "No end date; continues indefinitely"
  };
  return descriptions[type];
}

function getSupplierServiceDescription(service: SUPPLIER_SERVICE): string {
  const descriptions: Record<SUPPLIER_SERVICE, string> = {
    [SUPPLIER_SERVICE.ADVERTISING_SERVICES]: "Advertising services",
    [SUPPLIER_SERVICE.ARTS_CULTURE]: "Arts and culture services",
    [SUPPLIER_SERVICE.ASSET_TRACKING_SERVICES]: "Asset tracking services",
    [SUPPLIER_SERVICE.AUDIO_VISUAL_SERVICES]: "Audio and visual services",
    [SUPPLIER_SERVICE.AUDIT_SERVICES]: "Audit services",
    [SUPPLIER_SERVICE.BROADBAND_FIBER_WIMAX]: "Broadband fiber Wimax installation",
    [SUPPLIER_SERVICE.BTS_CONSTRUCTION]: "BTS construction/civil works",
    [SUPPLIER_SERVICE.BTS_LANDLORDS]: "BTS landlords",
    [SUPPLIER_SERVICE.BUILDING_CONSTRUCTION]: "Building construction services",
    [SUPPLIER_SERVICE.BUSINESS_CONSULTANCY]: "Business consultancy services",
    [SUPPLIER_SERVICE.CATERING_HOSPITALITY]: "Catering and hospitality services",
    [SUPPLIER_SERVICE.CLEANING_LANDSCAPING]: "Cleaning and landscaping services",
    [SUPPLIER_SERVICE.CLEANING_SERVICES]: "Cleaning services",
    [SUPPLIER_SERVICE.COMPANY]: "Company services",
    [SUPPLIER_SERVICE.COMPUTER_CONSUMABLES]: "Computer consumables",
    [SUPPLIER_SERVICE.CONSTRUCTION_PERMIT]: "Construction permit workers",
    [SUPPLIER_SERVICE.CONTRACTORS]: "Contractors",
    [SUPPLIER_SERVICE.DEALER]: "Dealer services",
    [SUPPLIER_SERVICE.DISBURSEMENTS]: "Disbursements - Others",
    [SUPPLIER_SERVICE.DISTRIBUTION]: "Distribution inbound & warehousing",
    [SUPPLIER_SERVICE.EDUCATION]: "Education services",
    [SUPPLIER_SERVICE.ELECTRICAL_FITTINGS]: "Electrical fittings",
    [SUPPLIER_SERVICE.EVENT_MANAGEMENT]: "Event management services",
    [SUPPLIER_SERVICE.FACILITIES_MAINTENANCE]: "Facilities maintenance & repair",
    [SUPPLIER_SERVICE.FLEET_MAINTENANCE]: "Fleet maintenance & repairs",
    [SUPPLIER_SERVICE.FLEET_MANAGEMENT]: "Fleet management services",
    [SUPPLIER_SERVICE.FLEET_FUEL]: "Fleet management-fuel",
    [SUPPLIER_SERVICE.FOREIGN_SERVICES]: "Foreign services",
    [SUPPLIER_SERVICE.FURNITURE_FITTINGS]: "Furniture and fittings",
    [SUPPLIER_SERVICE.GENERAL_CONSULTANCY]: "General consultancy services",
    [SUPPLIER_SERVICE.GENERAL_SUPPLIERS]: "General suppliers",
    [SUPPLIER_SERVICE.GOVERNMENT]: "Government services",
    [SUPPLIER_SERVICE.HEALTH]: "Health services",
    [SUPPLIER_SERVICE.HOSPITALITY]: "Hospitality services",
    [SUPPLIER_SERVICE.HR_SERVICES]: "HR services-staff welfare",
    [SUPPLIER_SERVICE.INSURANCE]: "Insurance services",
    [SUPPLIER_SERVICE.INTERCONNECT]: "Interconnect & roaming",
    [SUPPLIER_SERVICE.IT_APPLICATIONS]: "IT applications software",
    [SUPPLIER_SERVICE.IT_CLOUD]: "IT cloud services",
    [SUPPLIER_SERVICE.IT_LICENSES]: "IT enterprise licenses",
    [SUPPLIER_SERVICE.IT_INFRASTRUCTURE]: "IT infrastructure services",
    [SUPPLIER_SERVICE.IT_MAINTENANCE]: "IT maintenance & support",
    [SUPPLIER_SERVICE.IT_SECURITY]: "IT security services",
    [SUPPLIER_SERVICE.IT_IMPLEMENTATION]: "IT software implementation",
    [SUPPLIER_SERVICE.IT_VAS_DEV]: "IT/VAS dev prof services",
    [SUPPLIER_SERVICE.IT_VAS_HARDWARE]: "IT/VAS hardware supply",
    [SUPPLIER_SERVICE.IT_VAS_PLATFORMS]: "IT/VAS platforms",
    [SUPPLIER_SERVICE.IT_VAS_SECURITY]: "IT/VAS security",
    [SUPPLIER_SERVICE.IT_VAS_SUPPORT]: "IT/VAS support services",
    [SUPPLIER_SERVICE.KNOW_AND_GROW]: "Know and grow",
    [SUPPLIER_SERVICE.LEGAL_SERVICES]: "Legal services",
    [SUPPLIER_SERVICE.LINK_RENTAL]: "Link rental",
    [SUPPLIER_SERVICE.LOGISTICS]: "Logistics services",
    [SUPPLIER_SERVICE.MARKETING_ADVERT]: "Marketing & advert services",
    [SUPPLIER_SERVICE.MARKETING_ACTIVATIONS]: "Marketing activations",
    [SUPPLIER_SERVICE.MARKETING_SERVICES]: "Marketing services",
    [SUPPLIER_SERVICE.MOTOR_LEASING]: "Motor vehicle leasing",
    [SUPPLIER_SERVICE.MOTOR_PURCHASE]: "Motor vehicle purchase",
    [SUPPLIER_SERVICE.MOTOR_VEHICLES]: "Motor vehicles",
    [SUPPLIER_SERVICE.MUNICIPALITY]: "Municipality",
    [SUPPLIER_SERVICE.NETWORK_EQUIPMENT]: "Network equipment",
    [SUPPLIER_SERVICE.NETWORK_INFRA_ACC]: "Network infrastructure acc.",
    [SUPPLIER_SERVICE.NETWORK_INFRA_SERV]: "Network infrastructure serv.",
    [SUPPLIER_SERVICE.NETWORK_OPTIMIZATION]: "Network optimisation services",
    [SUPPLIER_SERVICE.NETWORK_POWER]: "Network power infrastructure",
    [SUPPLIER_SERVICE.OFFICE_CONSUMABLES]: "Office consumables",
    [SUPPLIER_SERVICE.OFFICE_FURNITURE]: "Office furniture",
    [SUPPLIER_SERVICE.OTHERS]: "Others",
    [SUPPLIER_SERVICE.PARTNERSHIP]: "Partnership",
    [SUPPLIER_SERVICE.PAYMENT_SERVICES]: "Payment services",
    [SUPPLIER_SERVICE.PN_VENDOR]: "PN_VENDOR",
    [SUPPLIER_SERVICE.POSTPAID]: "Postpaid",
    [SUPPLIER_SERVICE.PRINTING]: "Printing services",
    [SUPPLIER_SERVICE.PROFESSIONAL_TECHNICAL]: "Professional & technical",
    [SUPPLIER_SERVICE.PROFESSIONAL_MEMBERSHIP]: "Professional membership",
    [SUPPLIER_SERVICE.PROFESSIONAL_SUBSCRIPTIONS]: "Professional subscriptions",
    [SUPPLIER_SERVICE.PROPERTY_LEASING]: "Property leasing",
    [SUPPLIER_SERVICE.PROPERTY_SERVICES]: "Property professional services",
    [SUPPLIER_SERVICE.PRS_PROVIDERS]: "PRS providers",
    [SUPPLIER_SERVICE.RECRUITMENT]: "Recruitment services",
    [SUPPLIER_SERVICE.RELATED_PARTY]: "Related party",
    [SUPPLIER_SERVICE.RESEARCH]: "Research services",
    [SUPPLIER_SERVICE.RESIDENTIAL_LANDLORDS]: "Residential landlords",
    [SUPPLIER_SERVICE.ROAMING]: "Roaming",
    [SUPPLIER_SERVICE.SAFARICOM_INTERNAL]: "Safaricom internal supplier",
    [SUPPLIER_SERVICE.SECURITY_SERVICES]: "Security services",
    [SUPPLIER_SERVICE.SECURITY_SYSTEMS]: "Security systems & support",
    [SUPPLIER_SERVICE.SECURITY_GUARDING]: "Security/guarding services",
    [SUPPLIER_SERVICE.SITE_ACQUISITIONS]: "Site acquisitions sevices",
    [SUPPLIER_SERVICE.SPONSORSHIPS]: "Sponsorships",
    [SUPPLIER_SERVICE.STAFF_HIRING]: "Staff hiring services",
    [SUPPLIER_SERVICE.STAFF_TRANSPORT]: "Staff transport",
    [SUPPLIER_SERVICE.STATIONERY]: "Stationery and consumables",
    [SUPPLIER_SERVICE.STATUTORY]: "Statutory institutions",
    [SUPPLIER_SERVICE.STRATEGIC_CONSULTANCY]: "Strategic consultancy",
    [SUPPLIER_SERVICE.SUPPLY_TERMINALS]: "Supplyterminals devices",
    [SUPPLIER_SERVICE.T_SUPPLY]: "T supply",
    [SUPPLIER_SERVICE.TAX_AUTHORITY]: "Tax authority",
    [SUPPLIER_SERVICE.TAXI_SUPPLIER]: "Taxi supplier",
    [SUPPLIER_SERVICE.TERMINAL_DEVICES]: "Terminal devices",
    [SUPPLIER_SERVICE.TERMINALS]: "Terminals",
    [SUPPLIER_SERVICE.TRAINING]: "Training services",
    [SUPPLIER_SERVICE.TRAVEL_ACCOMMODATION]: "Travel & accomodation",
    [SUPPLIER_SERVICE.TRAVEL_MANAGEMENT]: "Travel management services",
    [SUPPLIER_SERVICE.UTILITIES]: "Utilities",
    [SUPPLIER_SERVICE.VAS_PLATFORMS]: "VAS platforms and solutions",
    [SUPPLIER_SERVICE.VENDOR]: "Vendor",
    [SUPPLIER_SERVICE.WASTE_MANAGEMENT]: "Waste management services"
  };
  return descriptions[service];
}

function getCurrencyDescription(currency: CURRENCY): string {
  const descriptions: Record<CURRENCY, string> = {
    [CURRENCY.ETB]: "Ethiopian Birr",
    [CURRENCY.EUR]: "Euro",
    [CURRENCY.KES]: "Kenyan Shilling",
    [CURRENCY.ZAR]: "South African Rand",
    [CURRENCY.GBP]: "British Pound Sterling",
    [CURRENCY.USD]: "United States Dollar"
  };
  return descriptions[currency];
}

function getCountryDescription(country: COUNTRY): string {
  const descriptions: Record<COUNTRY, string> = {
    [COUNTRY.AFGHANISTAN]: "Islamic Republic of Afghanistan",
    [COUNTRY.ALBANIA]: "Republic of Albania",
    [COUNTRY.ALGERIA]: "People's Democratic Republic of Algeria",
    [COUNTRY.ANDORRA]: "Principality of Andorra",
    [COUNTRY.ANGOLA]: "Republic of Angola",
    [COUNTRY.ANTIGUA_BARBUDA]: "Antigua and Barbuda",
    [COUNTRY.ARGENTINA]: "Argentine Republic",
    [COUNTRY.ARMENIA]: "Republic of Armenia",
    [COUNTRY.AUSTRALIA]: "Commonwealth of Australia",
    [COUNTRY.AUSTRIA]: "Republic of Austria",
    [COUNTRY.AZERBAIJAN]: "Republic of Azerbaijan",
    [COUNTRY.BAHAMAS]: "Commonwealth of The Bahamas",
    [COUNTRY.BAHRAIN]: "Kingdom of Bahrain",
    [COUNTRY.BANGLADESH]: "People's Republic of Bangladesh",
    [COUNTRY.BARBADOS]: "Barbados",
    [COUNTRY.BELARUS]: "Republic of Belarus",
    [COUNTRY.BELGIUM]: "Kingdom of Belgium",
    [COUNTRY.BELIZE]: "Belize",
    [COUNTRY.BENIN]: "Republic of Benin",
    [COUNTRY.BHUTAN]: "Kingdom of Bhutan",
    [COUNTRY.BOLIVIA]: "Plurinational State of Bolivia",
    [COUNTRY.BOSNIA_HERZEGOVINA]: "Bosnia and Herzegovina",
    [COUNTRY.BOTSWANA]: "Republic of Botswana",
    [COUNTRY.BRAZIL]: "Federative Republic of Brazil",
    [COUNTRY.BRUNEI]: "Brunei Darussalam",
    [COUNTRY.BULGARIA]: "Republic of Bulgaria",
    [COUNTRY.BURKINA_FASO]: "Burkina Faso",
    [COUNTRY.BURUNDI]: "Republic of Burundi",
    [COUNTRY.CAMBODIA]: "Kingdom of Cambodia",
    [COUNTRY.CAMEROON]: "Republic of Cameroon",
    [COUNTRY.CANADA]: "Canada",
    [COUNTRY.CAPE_VERDE]: "Republic of Cabo Verde",
    [COUNTRY.CENTRAL_AFRICAN_REPUBLIC]: "Central African Republic",
    [COUNTRY.CHAD]: "Republic of Chad",
    [COUNTRY.CHILE]: "Republic of Chile",
    [COUNTRY.CHINA]: "People's Republic of China",
    [COUNTRY.COLOMBIA]: "Republic of Colombia",
    [COUNTRY.COMOROS]: "Union of the Comoros",
    [COUNTRY.CONGO]: "Republic of the Congo",
    [COUNTRY.DEMOCRATIC_REPUBLIC_CONGO]: "Democratic Republic of the Congo",
    [COUNTRY.COSTA_RICA]: "Republic of Costa Rica",
    [COUNTRY.IVORY_COAST]: "Republic of Côte d'Ivoire",
    [COUNTRY.CROATIA]: "Republic of Croatia",
    [COUNTRY.CUBA]: "Republic of Cuba",
    [COUNTRY.CYPRUS]: "Republic of Cyprus",
    [COUNTRY.CZECH_REPUBLIC]: "Czech Republic",
    [COUNTRY.DENMARK]: "Kingdom of Denmark",
    [COUNTRY.DJIBOUTI]: "Republic of Djibouti",
    [COUNTRY.DOMINICA]: "Commonwealth of Dominica",
    [COUNTRY.DOMINICAN_REPUBLIC]: "Dominican Republic",
    [COUNTRY.ECUADOR]: "Republic of Ecuador",
    [COUNTRY.EGYPT]: "Arab Republic of Egypt",
    [COUNTRY.EL_SALVADOR]: "Republic of El Salvador",
    [COUNTRY.EQUATORIAL_GUINEA]: "Republic of Equatorial Guinea",
    [COUNTRY.ERITREA]: "State of Eritrea",
    [COUNTRY.ESTONIA]: "Republic of Estonia",
    [COUNTRY.ETHIOPIA]: "Federal Democratic Republic of Ethiopia",
    [COUNTRY.FIJI]: "Republic of Fiji",
    [COUNTRY.FINLAND]: "Republic of Finland",
    [COUNTRY.FRANCE]: "French Republic",
    [COUNTRY.GABON]: "Gabonese Republic",
    [COUNTRY.GAMBIA]: "Republic of The Gambia",
    [COUNTRY.GEORGIA]: "Georgia",
    [COUNTRY.GERMANY]: "Federal Republic of Germany",
    [COUNTRY.GHANA]: "Republic of Ghana",
    [COUNTRY.GREECE]: "Hellenic Republic",
    [COUNTRY.GRENADA]: "Grenada",
    [COUNTRY.GUATEMALA]: "Republic of Guatemala",
    [COUNTRY.GUINEA]: "Republic of Guinea",
    [COUNTRY.GUINEA_BISSAU]: "Republic of Guinea-Bissau",
    [COUNTRY.GUYANA]: "Co-operative Republic of Guyana",
    [COUNTRY.HAITI]: "Republic of Haiti",
    [COUNTRY.HONDURAS]: "Republic of Honduras",
    [COUNTRY.HONG_KONG]: "Hong Kong Special Administrative Region of China",
    [COUNTRY.HUNGARY]: "Hungary",
    [COUNTRY.ICELAND]: "Iceland",
    [COUNTRY.INDIA]: "Republic of India",
    [COUNTRY.INDONESIA]: "Republic of Indonesia",
    [COUNTRY.IRAN]: "Islamic Republic of Iran",
    [COUNTRY.IRAQ]: "Republic of Iraq",
    [COUNTRY.IRELAND]: "Ireland",
    [COUNTRY.ISRAEL]: "State of Israel",
    [COUNTRY.ITALY]: "Italian Republic",
    [COUNTRY.JAMAICA]: "Jamaica",
    [COUNTRY.JAPAN]: "Japan",
    [COUNTRY.JORDAN]: "Hashemite Kingdom of Jordan",
    [COUNTRY.KAZAKHSTAN]: "Republic of Kazakhstan",
    [COUNTRY.KENYA]: "Republic of Kenya",
    [COUNTRY.KIRIBATI]: "Republic of Kiribati",
    [COUNTRY.NORTH_KOREA]: "Democratic People's Republic of Korea",
    [COUNTRY.SOUTH_KOREA]: "Republic of Korea",
    [COUNTRY.KUWAIT]: "State of Kuwait",
    [COUNTRY.KYRGYZSTAN]: "Kyrgyz Republic",
    [COUNTRY.LAOS]: "Lao People's Democratic Republic",
    [COUNTRY.LATVIA]: "Republic of Latvia",
    [COUNTRY.LEBANON]: "Lebanese Republic",
    [COUNTRY.LESOTHO]: "Kingdom of Lesotho",
    [COUNTRY.LIBERIA]: "Republic of Liberia",
    [COUNTRY.LIBYA]: "State of Libya",
    [COUNTRY.LIECHTENSTEIN]: "Principality of Liechtenstein",
    [COUNTRY.LITHUANIA]: "Republic of Lithuania",
    [COUNTRY.LUXEMBOURG]: "Grand Duchy of Luxembourg",
    [COUNTRY.MACAU]: "Macao Special Administrative Region of China",
    [COUNTRY.NORTH_MACEDONIA]: "Republic of North Macedonia",
    [COUNTRY.MADAGASCAR]: "Republic of Madagascar",
    [COUNTRY.MALAWI]: "Republic of Malawi",
    [COUNTRY.MALAYSIA]: "Malaysia",
    [COUNTRY.MALDIVES]: "Republic of Maldives",
    [COUNTRY.MALI]: "Republic of Mali",
    [COUNTRY.MALTA]: "Republic of Malta",
    [COUNTRY.MARSHALL_ISLANDS]: "Republic of the Marshall Islands",
    [COUNTRY.MAURITANIA]: "Islamic Republic of Mauritania",
    [COUNTRY.MAURITIUS]: "Republic of Mauritius",
    [COUNTRY.MEXICO]: "United Mexican States",
    [COUNTRY.MICRONESIA]: "Federated States of Micronesia",
    [COUNTRY.MOLDOVA]: "Republic of Moldova",
    [COUNTRY.MONACO]: "Principality of Monaco",
    [COUNTRY.MONGOLIA]: "Mongolia",
    [COUNTRY.MONTENEGRO]: "Montenegro",
    [COUNTRY.MOROCCO]: "Kingdom of Morocco",
    [COUNTRY.MOZAMBIQUE]: "Republic of Mozambique",
    [COUNTRY.MYANMAR]: "Republic of the Union of Myanmar",
    [COUNTRY.NAMIBIA]: "Republic of Namibia",
    [COUNTRY.NAURU]: "Republic of Nauru",
    [COUNTRY.NEPAL]: "Federal Democratic Republic of Nepal",
    [COUNTRY.NETHERLANDS]: "Kingdom of the Netherlands",
    [COUNTRY.NEW_ZEALAND]: "New Zealand",
    [COUNTRY.NICARAGUA]: "Republic of Nicaragua",
    [COUNTRY.NIGER]: "Republic of Niger",
    [COUNTRY.NIGERIA]: "Federal Republic of Nigeria",
    [COUNTRY.NORWAY]: "Kingdom of Norway",
    [COUNTRY.OMAN]: "Sultanate of Oman",
    [COUNTRY.PAKISTAN]: "Islamic Republic of Pakistan",
    [COUNTRY.PALAU]: "Republic of Palau",
    [COUNTRY.PALESTINE]: "State of Palestine",
    [COUNTRY.PANAMA]: "Republic of Panama",
    [COUNTRY.PAPUA_NEW_GUINEA]: "Independent State of Papua New Guinea",
    [COUNTRY.PARAGUAY]: "Republic of Paraguay",
    [COUNTRY.PERU]: "Republic of Peru",
    [COUNTRY.PHILIPPINES]: "Republic of the Philippines",
    [COUNTRY.POLAND]: "Republic of Poland",
    [COUNTRY.PORTUGAL]: "Portuguese Republic",
    [COUNTRY.QATAR]: "State of Qatar",
    [COUNTRY.ROMANIA]: "Romania",
    [COUNTRY.RUSSIA]: "Russian Federation",
    [COUNTRY.RWANDA]: "Republic of Rwanda",
    [COUNTRY.SAINT_KITTS_NEVIS]: "Federation of Saint Christopher and Nevis",
    [COUNTRY.SAINT_LUCIA]: "Saint Lucia",
    [COUNTRY.SAINT_VINCENT_GRENADINES]: "Saint Vincent and the Grenadines",
    [COUNTRY.SAMOA]: "Independent State of Samoa",
    [COUNTRY.SAN_MARINO]: "Republic of San Marino",
    [COUNTRY.SAO_TOME_PRINCIPE]: "Democratic Republic of São Tomé and Príncipe",
    [COUNTRY.SAUDI_ARABIA]: "Kingdom of Saudi Arabia",
    [COUNTRY.SENEGAL]: "Republic of Senegal",
    [COUNTRY.SERBIA]: "Republic of Serbia",
    [COUNTRY.SEYCHELLES]: "Republic of Seychelles",
    [COUNTRY.SIERRA_LEONE]: "Republic of Sierra Leone",
    [COUNTRY.SINGAPORE]: "Republic of Singapore",
    [COUNTRY.SLOVAKIA]: "Slovak Republic",
    [COUNTRY.SLOVENIA]: "Republic of Slovenia",
    [COUNTRY.SOLOMON_ISLANDS]: "Solomon Islands",
    [COUNTRY.SOMALIA]: "Federal Republic of Somalia",
    [COUNTRY.SOUTH_AFRICA]: "Republic of South Africa",
    [COUNTRY.SOUTH_SUDAN]: "Republic of South Sudan",
    [COUNTRY.SPAIN]: "Kingdom of Spain",
    [COUNTRY.SRI_LANKA]: "Democratic Socialist Republic of Sri Lanka",
    [COUNTRY.SUDAN]: "Republic of the Sudan",
    [COUNTRY.SURINAME]: "Republic of Suriname",
    [COUNTRY.SWEDEN]: "Kingdom of Sweden",
    [COUNTRY.SWITZERLAND]: "Swiss Confederation",
    [COUNTRY.SYRIA]: "Syrian Arab Republic",
    [COUNTRY.TAIWAN]: "Republic of China (Taiwan)",
    [COUNTRY.TAJIKISTAN]: "Republic of Tajikistan",
    [COUNTRY.TANZANIA]: "United Republic of Tanzania",
    [COUNTRY.THAILAND]: "Kingdom of Thailand",
    [COUNTRY.EAST_TIMOR]: "Democratic Republic of Timor-Leste",
    [COUNTRY.TOGO]: "Togolese Republic",
    [COUNTRY.TONGA]: "Kingdom of Tonga",
    [COUNTRY.TRINIDAD_TOBAGO]: "Republic of Trinidad and Tobago",
    [COUNTRY.TUNISIA]: "Republic of Tunisia",
    [COUNTRY.TURKEY]: "Republic of Turkey",
    [COUNTRY.TURKMENISTAN]: "Turkmenistan",
    [COUNTRY.TUVALU]: "Tuvalu",
    [COUNTRY.UGANDA]: "Republic of Uganda",
    [COUNTRY.UKRAINE]: "Ukraine",
    [COUNTRY.UNITED_ARAB_EMIRATES]: "United Arab Emirates",
    [COUNTRY.UNITED_KINGDOM]: "United Kingdom of Great Britain and Northern Ireland",
    [COUNTRY.UNITED_STATES]: "United States of America",
    [COUNTRY.URUGUAY]: "Oriental Republic of Uruguay",
    [COUNTRY.UZBEKISTAN]: "Republic of Uzbekistan",
    [COUNTRY.VANUATU]: "Republic of Vanuatu",
    [COUNTRY.VATICAN_CITY]: "Vatican City State",
    [COUNTRY.VENEZUELA]: "Bolivarian Republic of Venezuela",
    [COUNTRY.VIETNAM]: "Socialist Republic of Vietnam",
    [COUNTRY.YEMEN]: "Republic of Yemen",
    [COUNTRY.ZAMBIA]: "Republic of Zambia",
    [COUNTRY.ZIMBABWE]: "Republic of Zimbabwe"
  };
  return descriptions[country];
}

