apiVersion: batch/v1
kind: CronJob
metadata:
  name: clm-cron
spec:
  schedule: "10 21 * * *" # Run daily at 10:00 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: contract-checker
              image: mdc1-sfcr.safaricomet.net/miniapp/clm-cron:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 3000
                  name: server
                  protocol: TCP
              envFrom:
                - configMapRef:
                    name: clm-config
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "60m"
                limits:
                  memory: "256Mi"
                  cpu: "120m"
          restartPolicy: OnFailure
          imagePullSecrets:
            - name: bot-harbor-cred
