apiVersion: v1
kind: Service
metadata:
  name: clm-db-service
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: clm-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
